import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs';

// Store active agent stream runners
const activeRuns = new Map();

export class AgentEngine {
  constructor(ws, sessionId) {
    this.ws = ws;
    this.sessionId = sessionId || `session-${Date.now()}`;
    this.isAborted = false;
  }

  abort() {
    this.isAborted = true;
    if (activeRuns.has(this.sessionId)) {
      const run = activeRuns.get(this.sessionId);
      if (run.process) {
        try {
          run.process.kill();
        } catch (e) {
          // ignore
        }
      }
      activeRuns.delete(this.sessionId);
    }
  }

  send(type, payload) {
    if (this.ws && this.ws.readyState === 1 && !this.isAborted) {
      this.ws.send(JSON.stringify({ type, sessionId: this.sessionId, payload }));
    }
  }

  async runPrompt(prompt, workspacePath = process.cwd(), model = 'Gemini 3.7 Flash', options = {}) {
    activeRuns.set(this.sessionId, this);
    this.isAborted = false;

    this.send('AGENT_STREAM_START', {
      prompt,
      model,
      timestamp: Date.now(),
    });

    try {
      // Step 1: Emit thinking / reasoning stream
      this.send('AGENT_THOUGHT_START', { timestamp: Date.now() });

      const thoughts = [
        `Analyzing user instruction: "${prompt}"...`,
        `Inspecting workspace context at ${workspacePath}...`,
        `Planning code generation, file updates, and live preview sync...`,
      ];

      for (const thought of thoughts) {
        if (this.isAborted) return;
        await new Promise((r) => setTimeout(r, 180));
        this.send('AGENT_THOUGHT_CHUNK', { text: `${thought}\n` });
      }

      this.send('AGENT_THOUGHT_END', { timestamp: Date.now() });

      const lowerPrompt = prompt.toLowerCase();
      let toolToRun = null;
      let targetFilePath = null;
      let liveContent = null;
      let prevContent = '';

      // Check if prompt is asking to create or edit a file/webpage
      if (
        lowerPrompt.includes('create') || 
        lowerPrompt.includes('write') || 
        lowerPrompt.includes('edit') || 
        lowerPrompt.includes('html') || 
        lowerPrompt.includes('page') ||
        lowerPrompt.includes('component')
      ) {
        const isHtml = lowerPrompt.includes('html') || lowerPrompt.includes('webpage') || lowerPrompt.includes('landing');
        const filename = isHtml ? 'preview.html' : 'example.js';
        targetFilePath = path.join(workspacePath, filename);

        if (fs.existsSync(targetFilePath)) {
          try {
            prevContent = fs.readFileSync(targetFilePath, 'utf-8');
          } catch (e) {
            prevContent = '';
          }
        }

        if (isHtml) {
          liveContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Live Webpage Preview</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-900 text-white min-h-screen flex items-center justify-center p-6 font-sans">
  <div class="max-w-md w-full bg-slate-800 border border-slate-700 rounded-2xl p-6 shadow-2xl space-y-4 text-center">
    <div class="w-12 h-12 rounded-xl bg-indigo-500/20 border border-indigo-500/30 flex items-center justify-center mx-auto text-indigo-400 font-bold text-lg">
      ✨
    </div>
    <h1 class="text-xl font-bold text-white tracking-tight">Antigravity Live Webpage</h1>
    <p class="text-xs text-slate-300">
      This page is rendered live in your right-hand Workspace File Viewer pane as the AI edits!
    </p>
    <div class="pt-2">
      <button class="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-semibold shadow-md transition-all">
        Explore Features
      </button>
    </div>
  </div>
</body>
</html>`;
        } else {
          liveContent = `// Auto-generated by Antigravity AI\n// Prompt: "${prompt}"\n\nexport function executeTask() {\n  console.log("Live file updated synchronously with AI stream.");\n  return {\n    success: true,\n    timestamp: new Date().toISOString(),\n  };\n}\n`;
        }

        toolToRun = {
          toolId: `tool-${Date.now()}-write`,
          name: 'write_to_file',
          args: {
            TargetFile: targetFilePath,
            CodeContent: liveContent,
            Description: `Generated content for "${prompt}"`,
          },
        };
      } else if (lowerPrompt.includes('file') || lowerPrompt.includes('list') || lowerPrompt.includes('dir')) {
        toolToRun = {
          toolId: `tool-${Date.now()}-list`,
          name: 'list_dir',
          args: { DirectoryPath: workspacePath },
        };
      } else if (lowerPrompt.includes('health') || lowerPrompt.includes('status') || lowerPrompt.includes('system')) {
        toolToRun = {
          toolId: `tool-${Date.now()}-health`,
          name: 'check_system_health',
          args: { platform: process.platform, arch: process.arch },
        };
      }

      if (toolToRun) {
        if (this.isAborted) return;
        this.send('AGENT_TOOL_START', toolToRun);

        // If tool is writing or editing a file, emit live file sync event
        if (toolToRun.name === 'write_to_file' && targetFilePath && liveContent) {
          try {
            fs.writeFileSync(targetFilePath, liveContent, 'utf-8');
          } catch (e) {
            console.error('Failed to write file:', e);
          }

          this.send('AGENT_FILE_EDIT_LIVE', {
            filePath: targetFilePath,
            fileName: path.basename(targetFilePath),
            content: liveContent,
            previousContent: prevContent,
            isWebpage: targetFilePath.endsWith('.html') || targetFilePath.endsWith('.svg'),
            timestamp: Date.now(),
          });
        }

        await new Promise((r) => setTimeout(r, 600));

        let toolOutput = '';
        if (toolToRun.name === 'write_to_file') {
          toolOutput = JSON.stringify({
            status: 'SUCCESS',
            filePath: targetFilePath,
            size: liveContent.length,
            message: 'File written and synced to workspace live.',
          }, null, 2);
        } else if (toolToRun.name === 'list_dir') {
          try {
            const files = fs.readdirSync(workspacePath);
            toolOutput = JSON.stringify({ files, total: files.length }, null, 2);
          } catch (e) {
            toolOutput = JSON.stringify({ error: e.message });
          }
        } else if (toolToRun.name === 'check_system_health') {
          toolOutput = JSON.stringify({
            node: process.version,
            memory: `${Math.round(process.memoryUsage().heapUsed / 1024 / 1024)}MB / ${Math.round(process.memoryUsage().heapTotal / 1024 / 1024)}MB`,
            uptime: `${Math.round(process.uptime())}s`,
            status: 'HEALTHY'
          }, null, 2);
        }

        this.send('AGENT_TOOL_RESULT', {
          toolId: toolToRun.toolId,
          name: toolToRun.name,
          output: toolOutput,
          status: 'SUCCESS',
        });
      }

      // Step 3: Stream main response tokens
      const fullResponse = this.generateResponse(prompt, workspacePath, toolToRun, targetFilePath);
      const chunks = fullResponse.match(/.{1,14}/g) || [fullResponse];

      for (const chunk of chunks) {
        if (this.isAborted) return;
        await new Promise((r) => setTimeout(r, 20));
        this.send('AGENT_STREAM_CHUNK', { text: chunk });
      }

      this.send('AGENT_STREAM_END', {
        completeResponse: fullResponse,
        timestamp: Date.now(),
      });
    } catch (err) {
      if (!this.isAborted) {
        this.send('AGENT_STREAM_ERROR', { error: err.message });
      }
    } finally {
      activeRuns.delete(this.sessionId);
    }
  }

  generateResponse(prompt, workspacePath, toolRun, targetFilePath) {
    if (toolRun && toolRun.name === 'write_to_file') {
      const filename = path.basename(targetFilePath);
      return `I have updated \`${filename}\` in your workspace.\n\n### ⚡ Live Sync Active\n- File: \`${targetFilePath}\`\n- The right-hand Workspace File Viewer pane has automatically loaded this file live.\n- You can inspect the code in **Edit** mode, compare changes in **Diff** mode, or render the live webpage in **Preview** mode!`;
    }

    if (toolRun && toolRun.name === 'list_dir') {
      return `I have inspected your workspace directory at \`${workspacePath}\`.\n\n### Workspace Overview\n- Directory is active and synced with the localhost harness.\n- All changes made in the harness will immediately reflect in your local filesystem.\n\nYou can ask me to create components, edit configuration files, or build web pages!`;
    }

    if (toolRun && toolRun.name === 'check_system_health') {
      return `### System & Harness Status\n\n- **Runtime**: Node.js \`${process.version}\`\n- **Platform**: \`${process.platform} (${process.arch})\`\n- **Gateway**: WebSocket Live on \`ws://localhost:3001/ws\`\n\nEverything is operating smoothly. What would you like to build next?`;
    }

    return `### Response\n\nI have processed your instruction: **"${prompt}"**.\n\nChanges are synced directly to your active workspace files in real time.`;
  }
}

export function stopSession(sessionId) {
  if (activeRuns.has(sessionId)) {
    const run = activeRuns.get(sessionId);
    run.abort();
    activeRuns.delete(sessionId);
    return true;
  }
  return false;
}
